feat: support async JS execution and ESM modules
squidfunk/iframe-worker pull request #583
Opened 2023-09-03 14:04 UTC by ThaUnknown

this implements what #522 wanted.

I'm not certain the `referrerPolicy` is required, but I added it regardless.

Additionally added support for ESM modules because ESM is cool.

General idea is that the entire script would be loaded from some CDN, this would mean it runs in a different origin than the website's main script, which would *hopefully* allow the worker to run async, this functionality is simply for browsers that don't support the `Origin-Agent-Cluster` header, so this would look something like:
```js
import IFrameWorker from 'https://esm.sh/iframe-worker'

const worker = new IFrameWorker('https://absolutedomain.com/myscript.js', { url: 'https://esm.sh/404', type: 'module' })
```
and if the `Origin-Agent-Cluster` is supported, re: we're only targetting chrome simply
```js
import IFrameWorker from 'iframe-worker'

const worker = new IFrameWorker('./myscript.js', { url: './404', type: 'module' })
```
would be enough

haven't actually tested it, this is just purely an idea from reading specifications x)

2023-09-19 07:15 UTC, squidfunk requested changes
Thanks for the PR! So we definitely need tests for this, and need to know whether it improves the situation. Could you add some tests we can run to verify that it works correctly?

2023-09-19 08:32 UTC, ThaUnknown commented
issue is, I have no clue how to write automated tests for this :)

2023-09-19 10:24 UTC, ThaUnknown commented
okay well, this didin't work

there's a fundamental issue here, doing document.write() changes origin to the origin of the script that ran it, so the only way this would work is if the iframe loaded an entire html file that's remote somewhere, that's CORS enabled, which means the developer would need to import the setup for the worker themselves in their html/js files via
```html
<script src='iframe-worker/runtime/setup.js'>
```
how should we create this kind of export?

2023-09-19 13:56 UTC, ThaUnknown commented
I don't know how to synthetically test frame drops in a browser, I could provide a reproduction case for human use, but not for automated detection, I don't know how to detect if code is running async

2023-09-19 14:52 UTC, squidfunk commented
We need some way to know whether it actually runs async and works to assess whether this is a good fit for this package. As I understand, you're proposing quite some fundamental changes to the API.

2023-10-10 05:54 UTC, squidfunk requested changes
Tests are still missing.

2023-10-10 07:21 UTC, ThaUnknown commented
I still have no clue how to set up tests for cross-origin async JS execution, if you have any ideas do share them, but I don't know how to create that on local tests

2024-01-10 02:07 UTC, squidfunk commented
> I'm not certain the referrerPolicy is required, but I added it regardless.
> Additionally added support for ESM modules because ESM is cool.

We're currently not planning to move forward with this, because we want to keep this library as tiny as possible. This means we get rid of everything that is not required or necessary. This library is primarily intended to make workers work on `file://`.

2024-01-10 02:07 UTC, closed without merging